WebAppRestaurant/Models/Register.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string role { get; set; }
    }
}

WebAppRestaurant/Controllers/RegistersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppRestaurant.Models;

namespace WebAppRestaurant.Controllers
{
    public class RegistersController : Controller
    {
        private RestaurantDBEntities3 db = new RestaurantDBEntities3();

        // GET: Registers
        public ActionResult Index()
        {
           /* if (Session["session"] == null)
            {
                return RedirectToAction("login", "Admin");
            }*/
            return View(db.Registers.ToList());
        }

        // GET: Registers/Details/5
        public ActionResult Details(string id)
        {   

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = db.Registers.Find(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            return View(register);
        }

        // GET: Registers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Registers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,Password,PhoneNumber,role")] Register register)
        {
            /*if (Session["session"] == null)
            {
                return RedirectToAction("login", "Admin");
            }*/
            if (ModelState.IsValid)
            {
                db.Registers.Add(register);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(register);
        }

        // GET: Registers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = db.Registers.Find(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            return View(register);
        }

        // POST: Registers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
      //  [Route("EditThis")]
        public ActionResult Edit([Bind(Include = "UserName,Password,PhoneNumber,role")] Register register)
        {
            try { 
            if (ModelState.IsValid)
            {
                db.Entry(register).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(register);
            }
            catch(Exception e)
            {
                return View(e);
            }
        }

        // GET: Registers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Register register = db.Registers.Find(id);
            if (register == null)
            {
                return HttpNotFound();
            }
            return View(register);
        }

        // POST: Registers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Register register = db.Registers.Find(id);
            db.Registers.Remove(register);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppRestaurant/Views/Admin/Home_SuperAdmin.cshtml
@model IEnumerable<WebAppRestaurant.Models.Register>

@{
    ViewBag.Title = "Home_SuperAdmin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <body style="background-color:bisque ">
    <center>
        <h2>SuperAdmin Home Page</h2>
    </center>
    <center>
        <table style="border-collapse: separate; border-spacing: 0 15px">

            <tr>

                <td><button> @Html.ActionLink("Add Admin", "Register") </button></td>

            </tr>

            <tr>

                <td><button> @Html.ActionLink("View Admin", "Index", "Registers") </button>  </td>

            </tr>

        </table>

    </center>
</body>

WebAppRestaurant/Views/Admin/Register.cshtml
@model WebAppRestaurant.Models.Register

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/partialView.cshtml";
}

<style>

    .outlet {
        text-align: left;
        background-color: blanchedalmond;
        width: 600px;
        border: 20px solid #ffd800;
        padding: 50px;
        margin: auto;
        
    }
</style>


<body background="~/Content/bb1.jpg">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="outlet">
            <center>
                <div class="form-horizontal">

                    <center>
                        <h3><strong>Register</strong></h3>
                    </center>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.role, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.role, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.role, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Register" class="btn btn-default" />
                        </div>
                    </div>

                    <div id="navlink">
                        @Html.ActionLink("Already have an Account ? Login", "login", "Admin")
                    </div>

                </div>
            </center>
        </div>
    }
</body>

WebAppRestaurant/Views/Admin/login.cshtml
@model WebAppRestaurant.Models.Register

@{
    ViewBag.Title = "login";
    Layout = "~/Views/Shared/partialView.cshtml";
}

<style>

    .outlet {
        text-align: left;
        background-color: blanchedalmond;
        width: 600px;
        border: 15px solid #ffd800;
        padding: 50px;
        margin: auto;
    }
</style>

<body background="~/Content/bbb.jpg">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    <div style="text-align:center" class="outlet">
        <center>
            <div class="form-horizontal">
                <center>
                    <h3><strong>LogIn</strong></h3>
                </center>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*    <div class="form-group">
                @Html.LabelFor(model => model.role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.role, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.role, "", new { @class = "text-danger" })
                </div>
            </div>*@

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Login" class="btn btn-default" />
                    </div>
                </div>
                <div id="navlink">
                    @Html.ActionLink("Dont Have an Account ? Register", "Register", "Admin")
                </div>

                <div id="errorMessage">
                    @ViewBag.Message
                </div>

            </div>
            </center>
</div>
            }

    </body>